name: intrapair_task
description: An app build with the stacked framework


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  stacked: ^3.2.7
  stacked_services: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2


flutter:


  uses-material-design: true

  
  assets:
   - assets/svgs/
   - assets/pngs/
   - assets/fonts/
  

 
  fonts:
     - family: ViceCitySans
       fonts:
         - asset: assets/fonts/ViceCitySans.otf
         
          
     


